- hosts: localhost
  gather_facts: false

  vars_file:
    - vars/main.yml

  tasks:
    - name: Add host to inventory
      ansible.builtin.add_host:
        name: "{{ kvm_host.name }}"
        ansible_host: "{{ kvm_host.ansible_host }}"
        ansible_user: "{{ kvm_host.ansible_user }}"
        ansible_ssh_common_args: -o "UserKnownHostsFile=/dev/null" -o StrictHostKeyChecking=no -i {{ kvm_host.ansible_ssh_private_key_file }}
        groups: "{{ kvm_host.groups }}"

    - name: Import 'cloud.gcp_ops.clone_on_prem_vm' role
      ansible.builtin.import_role:
        name: cloud.gcp_ops.clone_on_prem_vm
      vars:
        clone_on_prem_vm_source_vm_name: "{{ clone_on_prem_vm_source_vm_name }}"
        clone_on_prem_vm_dest_image_name: "{{ clone_on_prem_vm_dest_image_name }}"
        clone_on_prem_vm_local_image_path: "{{ clone_on_prem_vm_local_image_path }}"
        clone_on_prem_vm_overwrite: "{{ clone_on_prem_vm_overwrite }}"
      delegate_to: kvm

    - name: Import 'cloud.gcp_ops.import_image_and_run_gcp_instance' role
      ansible.builtin.import_role:
        name: cloud.gcp_ops.import_image_and_run_gcp_instance
      vars:
        import_image_and_run_gcp_instance_bucket_name: "{{ import_image_and_run_gcp_instance_bucket_name }}"
        import_image_and_run_gcp_instance_image_path: "{{ import_image_and_run_gcp_instance_image_path }}"
        import_image_and_run_gcp_instance_instance_name: "{{ import_image_and_run_gcp_instance_instance_name }}"
        import_image_and_run_aws_instance_machine_type: "{{ import_image_and_run_aws_instance_machine_type }}"
        import_image_and_run_aws_instance_import_image_name: "{{ import_image_and_run_aws_instance_import_image_name }}"
        import_image_and_run_gcp_instance_deletion_protection: "{{ import_image_and_run_gcp_instance_deletion_protection }}"
        import_image_and_run_gcp_instance_labels: "{{ import_image_and_run_gcp_instance_labels }}"
        import_image_and_run_gcp_instance_metadata: "{{ import_image_and_run_gcp_instance_metadata }}"
        import_image_and_run_gcp_instance_machine_type: "{{ import_image_and_run_gcp_instance_machine_type }}"
        import_image_and_run_gcp_instance_network_interfaces: "{{ import_image_and_run_gcp_instance_network_interfaces }}"
        import_image_and_run_gcp_instance_scheduling: "{{ import_image_and_run_gcp_instance_scheduling }}"
        import_image_and_run_gcp_instance_service_accounts: "{{ import_image_and_run_gcp_instance_service_accounts }}"
        import_image_and_run_gcp_instance_tags: "{{ import_image_and_run_gcp_instance_tags }}"
        import_image_and_run_gcp_zone: "{{ import_image_and_run_gcp_zone }}"
